version: "3"
services:
  mysqldb:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: testopenai123
      MYSQL_DATABASE: task_db
      # MYSQL_ROOT_HOST: '%'
    container_name: mysql_container_test
    ports:
      - "3306:3306"
    networks:
      - backend

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "5000:5000"
    depends_on:
      - mysqldb
    networks:
      - backend
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:testopenai123@mysqldb:3306/task_db
    restart: always

networks:
  backend:
    driver: bridge
